apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
  annotations:
    webhookconverted: Webhook converted From oda.tmforum.org/v1beta3 to oda.tmforum.org/v1
spec:
  componentMetadata:
    id: {{.Values.component.id}}
    name: {{.Values.component.name}}
    version: {{.Values.component.version}}
    description: >-
      TMF669 Party Role API wrapped as an ODA component to be used as the Reference Implementation for the mandatory dependent API of the TMFC028 Party Management Reference Implementation component
    functionalBlock: {{.Values.component.functionalBlock}}
    publicationDate: {{.Values.component.publicationDate}}
    status: specified
    maintainers:
      - name: TM Forum
        email: components@tmforum.org
    owners:
      - name: TM Forum
        email: components@tmforum.org
  coreFunction:
    exposedAPIs:
      - name: partyrolemanagement
        id: TMF669
        specification:
          - url: >-
              https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        implementation: {{.Release.Name}}-nonsecuritypartyroleapi
        apiType: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
        port: 8080
        gatewayConfiguration: {}
    dependentAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction:
    exposedAPIs: []
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: {{.Values.security.canvasSystemRole}}
    exposedAPIs: []
    